### ISSUE TITLE
¿Cómo subimos imágenes?

### ISSUE THREAD

**Issue by rubenrivera** [g3rv4/help-pages#13]
El artículo de ayuda [reduce-ads.md](https://github.com/g3rv4/help-pages/blob/master/reduced-ads.md) incluye un par de imágenes. Si bien en ambas es visible texto en inglés, la primera no es tan importante colocarla en español pues su finalidad es señalar las áreas, pero la segunda muestra la opción a la que se refiere una sección del artículo

![](https://i.stack.imgur.com/6b6yZ.png)

El reemplazo podría ser el siguiente:

![](https://drive.google.com/a/rubenrivera.mx/uc?id=1vwnLfdWJTXqSbonT8YCg4xRiszVXkral&export=download)

**Comment by g3rv4** [comment]
Las imágenes tienen que estar hosteadas en imgur (como todas las imágenes de las preguntas).

Para eso, lo mejor sería que:

* Arranques una pregunta
* Subas las imágenes a la pregunta
* Copies las urls de las imágenes

Esas urls sirven para ser usadas en el centro de ayuda :)

**Comment by rubenrivera** [comment]
@g3rv4  Hecho.

Acá el link a la pregunta https://es.meta.stackoverflow.com/q/3352/65.

Ya se envió el PR con el URL de la imagen en IMGUR.
