### ISSUE TITLE
Can you add all the articles in Centro de Ayuda?

### ISSUE THREAD

**Issue by fedorqui** [g3rv4/help-pages#23]
Likewise in #22, it would be good to have them all since many links point to English pages, and some are even buggy (eg in https://es.stackoverflow.com/help/bounty _de entre las mostradas en una lista_ should point to https://stackoverflow.blog/2011/09/bounty-reasons-and-post-notices/, currently there is a typo and it links to a non existing page).

**Comment by g3rv4** [comment]
Adding them is a manual process, so adding all of them “just in case” seems like a high time investment activity with questionable returns.

If you have some pages, please add their urls and I’ll add them... it’s not like I take too long to add them, right?

**Comment by fedorqui** [comment]
As you wish. As seen in the answers to [¿Qué enlaces de las páginas del Centro de Ayuda apuntan a artículos en inglés?](https://es.meta.stackoverflow.com/q/3469/83), almost every page in the Help center has some links to English pages. Not to mention that they tend to need quite some improvements on translations.

Anyway, since this is something that will take long, I will focus on asking for those pages that become needed.
