### ISSUE TITLE
Can you add the /moderator-agreement page?

### ISSUE THREAD

**Issue by fedorqui** [g3rv4/help-pages#24]
As seen in https://es.stackoverflow.com/legal/moderator-agreement, the page is entirely in English. Could you add it to the repo? This is linked from a page in the Centro de Ayuda → https://es.stackoverflow.com/help/site-moderators

**Comment by g3rv4** [comment]
This is not a help page, it's a regular view that needs to be localized :)

Please add a question on meta with the tag `agregar-a-transifex`. Once it's localized, it will be available for translation at traducir.win

(on these cases, I need to submit a PR on my spare time that will be reviewed by people on the core team... so it's going to take a while)
