### ISSUE TITLE
Pense mejor sobre mi pregunta. Puedo borrarla?

### ISSUE THREAD

**Issue by topcatarg** [g3rv4/help-pages#27]
Hay que traducir: 

https://es.stackoverflow.com/help/what-to-do-instead-of-deleting-question

**Comment by ShadowPaz** [comment]
@topcatarg he ayudado a traducir el contenido, pero no se cual es el siguiente paso para poder hacer el pull request

**Comment by g3rv4** [comment]
agrego el md el lunes (ando de viaje)

**Comment by g3rv4** [comment]
Lista para traducir! cc @iuninefrendor
