### ISSUE TITLE
¿Podrías añadir el artículo 'vote-down' de los privilegios?

### ISSUE THREAD

**Issue by fedorqui** [g3rv4/help-pages#29]
https://es.stackoverflow.com/help/privileges/vote-down

En https://es.meta.stackoverflow.com/a/3789/83 me he dado cuenta de que hay un texto incompleto:

Donde dice
> Los votos negativos te quitan 1 de reputación a ti, el votante.

debería decir

> Los votos negativos en respuestas te quitan 1 de reputación a ti, el votante.

En SO está bien: https://stackoverflow.com/help/privileges/vote-down

**Comment by g3rv4** [comment]
listop!
