### ISSUE TITLE
¿Podrías añadir el artículo "What is Flair?" sobre la imagen de usuario?

### ISSUE THREAD

**Issue by fedorqui** [g3rv4/help-pages#31]
En https://es.stackoverflow.com/help/flair aparece un artículo titulado "What is Flair?". Parece nuevo y no está en este repositorio para poderlo traducir. ¿Podrías añadirlo? ¡Gracias!

**Comment by rafabmr** [comment]
@fedorqui interesante el saber como se traduciría la palabra "Flair" :hushed:

**Comment by fedorqui** [comment]
@iuninefrendor también pensé eso jeje. Veo en traducir.win que aparece como _miniperfil_ (https://traducir.win/filters?sourceRegex=%28%3Fi%29flair).
