### ISSUE TITLE
Faltan traducciones a las referencias de etiqueta de "whats-meta"

### ISSUE THREAD

**Issue by rafabmr** [g3rv4/help-pages#39]
Artículo: https://es.stackoverflow.com/help/whats-meta
En Meta las traducciones a esas etiquetas ya están 

- [feature-request]  >>> [característica-nueva]
- [support] >>> [soporte]
- [discussion] >>> [discusión]

![captura de pantalla](https://i.stack.imgur.com/Av7i3.png)

**Comment by g3rv4** [comment]
Listo! actualizá `whats-meta.md` y mandame un PR
